FROM python:3.9-slim-bullseye

WORKDIR /app

COPY packages.txt ./packages.txt

RUN pip install --upgrade pip
RUN pip install -r packages.txt

EXPOSE 8501

COPY . /app

ENTRYPOINT ["python"]

CMD ["app.py"]

############################ Extend image ###############

FROM challenge_pipreqs:latest

WORKDIR /app
COPY . /app

ENTRYPOINT ["python"]

CMD ["app.py"]